# Generated by Django 3.2.2 on 2021-05-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_group_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user and author restraint',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='user and following restraint'),
        ),
    ]
